import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<body className={inter.className}>
				<nav className="flex items-center text-white justify-between h-navbar bg-accent">
					<div>Fondos Europeos</div>
					<div>Fondos Europeos</div>
				</nav>
				{children}
			</body>
		</html>
	);
}
